
sudo su - -c "R -e \"install.packages('devtools', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('Rcpp', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('RcppEigen', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('ggplot2', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('Cairo', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('evaluate', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('formatR', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('highr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('markdown', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('yaml', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('htmltools', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('knitr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('rmarkdown', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('RColorBrewer', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -e \"source('http://bioconductor.org/biocLite.R'); biocLite('BiocParallel')\""
sudo su - -c "R -e \"source('http://bioconductor.org/biocLite.R'); biocLite('Biobase')\""
sudo su - -c "R -e \"source('http://bioconductor.org/biocLite.R'); biocLite('EBSeq')\""
sudo su - -c "R -e \"source('http://bioconductor.org/biocLite.R'); biocLite('monocle')\""
sudo su - -c "R -e \"source('http://bioconductor.org/biocLite.R'); biocLite('sincell')\""
sudo su - -c "R -e \"source('http://bioconductor.org/biocLite.R'); biocLite('scde')\""
sudo su - -c "R -e \"source('http://bioconductor.org/biocLite.R'); biocLite('scran')\""
sudo su - -c "R -e \"source('http://bioconductor.org/biocLite.R'); biocLite('scater')\""
sudo su - -c "R -e \"devtools::install_github('kdkorthauer/scDD')\""
